### ISSUE TITLE
Additional "View Page Info" context menu

### ISSUE THREAD

**Issue by robbely** [agoupinets/view-image-context-menu-item#17]
Would it be possible to add the "View Page Info" context menu item that recently got removed by mozilla?

It can still be reached from the tools menu and using ctrl-i, but there are a lot of people (including myself) with muscle memory that still goes to the context menu first.

**Comment by agoupinets** [comment]
HI @robbely - I may take a look, but this falls a bit outside the scope of the add-on's purpose. If its not difficult to add I may just throw it in (no clue how firefox handles that popup or how to invoke it programatically at this point)

**Comment by agoupinets** [comment]
Searching around, it appears that there is no way to programmatically invoke the "Page Info" dialog using [WebExtensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API), as such there would be no way to code an add-on to be able to open it.

The closest I can find is there is a config option `browser.menu.showViewImageInfo` that adds a menu item to vanilla images to open the Page Info dialog to the Media tab:
![image](https://github.com/agoupinets/view-image-context-menu-item/assets/49403902/90e16c5e-f309-4794-821d-8f0c5957b47d)
Its a far cry from the always present "View Page Info" but there doesn't appear to be anything that can be done to readd the option using extensions.

If you come across any potential solutions, feel free to reopen the issue.

**Comment by robbely** [comment]
OK, many thanks for taking the time to check though :)
I'll let you know if I do find anything

**Comment by robbely** [comment]
Using the "Browser Console" - it looks like the menu item has an ID of "menu-tools-page-info". 

Here is the raw extracted code it that helps at all:`<menuitem xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" id="menu_pageInfo" key="key_viewInfo" command="View:PageInfo" data-l10n-id="menu-tools-page-info" label="Page Info" accesskey="I" acceltext="Ctrl+I"><label class="menu-text" crop="end" aria-hidden="true" value="Page Info" accesskey="I"/><hbox class="menu-accel-container" aria-hidden="true"><label class="menu-accel" value="Ctrl+I"/></hbox></menuitem>`
